version: '3.0'
services:
  mysterious:
    build:
      context: .
      dockerfile: Dockerfile
    image: crpi-0k05wk3jdatinndt.cn-chengdu.personal.cr.aliyuncs.com/zoeakk/mysterious:${MYSTERIOUS_VERSION}